# EJERCICIO INSURANCE

In [ ]:
import numpy as np
import pandas as pd

## Cargar datos

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_insurance = pd.read_csv('/content/drive/MyDrive/insurance.csv')

In [ ]:
df_insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df_insurance.loc[0:2,['age','sex','region']]

   age     sex     region
0   19  female  southwest
1   18    male  southeast
2   28    male  southeast

In [ ]:
df_insurance.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
df_insurance.iloc[0:3, [0,1,5]]

   age     sex     region
0   19  female  southwest
1   18    male  southeast
2   28    male  southeast

In [ ]:
df_insurance.loc[df_insurance.charges>=4000,:]

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
6      46  female  33.440         1     no  southeast   8240.58960
7      37  female  27.740         3     no  northwest   7281.50560
...   ...     ...     ...       ...    ...        ...          ...
1330   57  female  25.740         2     no  southeast  12629.16560
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1337   61  female  29.070         0    yes  northwest  29141.36030

[1069 rows x 7 columns]

In [ ]:
df_insurance.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
df_insurance.loc[df_insurance.region=='northwest', 'age' : 'region']

      age     sex     bmi  children smoker     region
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
7      37  female  27.740         3     no  northwest
9      60  female  25.840         0     no  northwest
24     37    male  28.025         2     no  northwest
...   ...     ...     ...       ...    ...        ...
1319   39  female  26.315         2     no  northwest
1320   31    male  31.065         3     no  northwest
1324   31    male  25.935         1     no  northwest
1333   50    male  30.970         3     no  northwest
1337   61  female  29.070         0    yes  northwest

[325 rows x 6 columns]

In [ ]:
# forma "antigua"
df_insurance[df_insurance.region=='northwest'][['age', 'smoker']]

      age smoker
3      33     no
4      32     no
7      37     no
9      60     no
24     37     no
...   ...    ...
1319   39     no
1320   31     no
1324   31     no
1333   50     no
1337   61    yes

[325 rows x 2 columns]

Necesito saber de mi dataframe el nº de filas, nº de columnas,  nombres de las columnas, nº de valores válidos (no nulos) y por último el tipo detectado de cada columna.

a) ¿Qué método de dataframe ya visto utilizarias?
b) aplicalo al dataframe "insurance"

In [ ]:
df_insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
df_insurance.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [ ]:
len(df_insurance)

1338

In [ ]:
df_insurance.shape

(1338, 7)

In [ ]:
df_insurance.shape[1]

7

In [ ]:
df_insurance.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

Contestar a las siguientes preguntas:
- ¿Cual es la media de los cargos médicos? ¿Y la desviación típica o standar (std)? Podrias decir con tus palabras si los datos estan más concentrados, o al contrario, más distribuidos respecto de la media?
- Valores máximo y mínimos de hijos (children)
- ¿Cual es la mediana de la edad del tomador?

In [ ]:
df_insurance.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
df_insurance.describe().applymap(int)

<ipython-input-21-d6b842fbb7f3>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_insurance.describe().applymap(int)

        age   bmi  children  charges
count  1338  1338      1338     1338
mean     39    30         1    13270
std      14     6         1    12110
min      18    15         0     1121
25%      27    26         0     4740
50%      39    30         1     9382
75%      51    34         2    16639
max      64    53         5    63770

In [ ]:
df_insurance.describe(include=['object'])

         sex smoker     region
count   1338   1338       1338
unique     2      2          4
top     male     no  southeast
freq     676   1064        364

Determinar cual es el valor mas frecuenta de la columna "smoker" y con que frecuencia. ¿Diría que es un valor factible (posible, real)?

In [ ]:
df_insurance.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
df_insurance.groupby('sex')['bmi'].agg('mean')

sex
female    30.377749
male      30.943129
Name: bmi, dtype: float64

In [ ]:
df_insurance.groupby('sex')['bmi'].agg(['min','max'])

           min    max
sex
female  16.815  48.07
male    15.960  53.13

In [ ]:
df_insurance.groupby('sex')[['bmi','smoker']].agg({'bmi':'mean','smoker': 'count'})

              bmi  smoker
sex
female  30.377749     662
male    30.943129     676