# PRÁCTICA PANDAS

Vamos a trabajar con un **conjunto de datos público "adults"** con datos del censo de los Estados Unidos, que contiene distintas variables de la población. El fin que se busca es el de clasificar las observaciones segun la variable Ingresos (income), variable dicotómica que indica si son menores o iguales a 50000 $ o bien superiores (“<=50K” o ">50K).

Nosotros en este punto del curso **como práctica de la librería "Pandas" que acabamos de ver, vamos simplemente a echarle un vistazo y a corregir y mejorar algunos aspectos del mismo.**

Los **datos** se encuentran en el archivo **"adult.data"**. **Necesitamos también examinar el archivo "adult.names" que describe el dataset para poder cargar los datos correctamente.**

## CARGA DE LOS DATOS

In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline


import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
ruta = '/content/drive/MyDrive/ESPECIALISTA IA/adult.data'

df_adult = pd.read_csv(ruta, \
                       header= None, \
                       names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status','occupation', \
                                'relationship', 'race', 'sex','capital-gain', 'capital-loss', 'hours-per-week', \
                                'native-country', 'income'])

In [ ]:
df_adult.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
df_adult.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [ ]:
 # EJEMPLO SUSTITUIR UN CARACTER (espacio en blanco, guion medio) en los
# NOMBRES DE COLUMNAS

df_adult.columns = [columna.replace("-","_") for columna in df_adult.columns.to_list()]

df_adult.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

## EXPLORAR DATAFRAME

In [ ]:
df_adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [ ]:
#contenido nuevo: cambio de tipo
df_adult['education_num'] = df_adult['education_num'].astype('str')

df_adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  object
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(5), object(10)
memory usage: 3.7+ MB

#### Hay determinadas columnas que no nos interesan, las vamos a eliminar:

- fnlwgt: (adult.names) dato interno sin relevancia analitica
- education_num: lo quito, ya tengo columna "education"

In [ ]:
df_adult.drop(columns=['fnlwgt', 'education_num'], inplace=True)

df_adult.columns

Index(['age', 'workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'capital_gain', 'capital_loss',
       'hours_per_week', 'native_country', 'income'],
      dtype='object')

In [ ]:
df_adult.duplicated().sum()

np.int64(3465)

In [ ]:
df_adult.drop_duplicates(inplace=True)

In [ ]:
df_adult.duplicated().sum()

np.int64(0)

**Para manejar más fácil los datos suele ser util separar las variables por tipo:**

In [ ]:
variables_numericas = df_adult.select_dtypes(exclude=['object']).columns.to_list()

variables_numericas

['age', 'capital_gain', 'capital_loss', 'hours_per_week']

In [ ]:
variables_categoricas = df_adult.select_dtypes(include=['object']).columns.to_list()

variables_categoricas

['workclass',
 'education',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native_country',
 'income']

In [ ]:
target = 'income'

In [ ]:
np.quantile(df_adult.capital_gain, 0.90)

np.float64(0.0)

In [ ]:
df_adult.describe()

                age  capital_gain  capital_loss  hours_per_week
count  29096.000000  29096.000000  29096.000000    29096.000000
mean      39.251340   1197.802206     97.175179       40.637820
std       13.687157   7778.225220    424.008232       12.735418
min       17.000000      0.000000      0.000000        1.000000
25%       28.000000      0.000000      0.000000       40.000000
50%       38.000000      0.000000      0.000000       40.000000
75%       48.000000      0.000000      0.000000       45.000000
max       90.000000  99999.000000   4356.000000       99.000000

<font color="red">Columnas "Capital gain" y "Capital Loss" presentan una distribución muy irregular (hasta percentil 90% todos son ceros) y valor máximo sospecha de error. Claros
candidatos a eliminar, pendiente de las gráficas.

En el caso de "Hours per week", valor máx sospecha de outliers, a falta de posteriores estudios

In [ ]:
df_adult.describe(include=['object'])

,workclass,education,marital_status,occupation,relationship,race,sex,native_country,income
count,29096,29096,29096,29096,29096,29096,29096,29096,29096
unique,9,16,7,15,6,5,2,42,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,19621,8886,13249,3885,11506,24438,19246,25721,21886

In [ ]:
variables_categoricas

['workclass',
 'education',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native_country',
 'income']

In [ ]:
print(df_adult['workclass'].unique())
print(df_adult['workclass'].value_counts())

[' State-gov' ' Self-emp-not-inc' ' Private' ' Federal-gov' ' Local-gov'
 ' ?' ' Self-emp-inc' ' Without-pay' ' Never-worked']
workclass
Private             19621
Self-emp-not-inc     2473
Local-gov            2040
?                    1632
State-gov            1272
Self-emp-inc         1091
Federal-gov           946
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [ ]:
variables_categoricas

['workclass',
 'education',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native_country',
 'income']

In [ ]:
for categorica in variables_categoricas:

    print(f'Variable {categorica.upper()}:')
    print('Valores unicos: ')
    print(df_adult[categorica].unique(), end='\n'*2)
    print(df_adult[categorica].value_counts(), end='\n'*2)

Variable WORKCLASS:
Valores unicos:
[' State-gov' ' Self-emp-not-inc' ' Private' ' Federal-gov' ' Local-gov'
 ' ?' ' Self-emp-inc' ' Without-pay' ' Never-worked']

workclass
Private             19621
Self-emp-not-inc     2473
Local-gov            2040
?                    1632
State-gov            1272
Self-emp-inc         1091
Federal-gov           946
Without-pay            14
Never-worked            7
Name: count, dtype: int64

Variable EDUCATION:
Valores unicos:
[' Bachelors' ' HS-grad' ' 11th' ' Masters' ' 9th' ' Some-college'
 ' Assoc-acdm' ' Assoc-voc' ' 7th-8th' ' Doctorate' ' Prof-school'
 ' 5th-6th' ' 10th' ' 1st-4th' ' Preschool' ' 12th']

education
HS-grad         8886
Some-college    6378
Bachelors       4810
Masters         1653
Assoc-voc       1331
11th            1056
Assoc-acdm      1053
10th             867
7th-8th          629
Prof-school      566
9th              507
12th             414
Doctorate        402
5th-6th          328
1st-4th          166
Preschool         50
Name: count, dtype: int64

Variable MARITAL_STATUS:
Valores unicos:
[' Never-married' ' Married-civ-spouse' ' Divorced'
 ' Married-spouse-absent' ' Separated' ' Married-AF-spouse' ' Widowed']

marital_status
Married-civ-spouse       13249
Never-married             9173
Divorced                  4237
Separated                 1014
Widowed                    982
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

Variable OCCUPATION:
Valores unicos:
[' Adm-clerical' ' Exec-managerial' ' Handlers-cleaners' ' Prof-specialty'
 ' Other-service' ' Sales' ' Craft-repair' ' Transport-moving'
 ' Farming-fishing' ' Machine-op-inspct' ' Tech-support' ' ?'
 ' Protective-serv' ' Armed-Forces' ' Priv-house-serv']

occupation
Prof-specialty       3885
Exec-managerial      3719
Adm-clerical         3340
Craft-repair         3298
Sales                3270
Other-service        2996
Machine-op-inspct    1702
?                    1639
Transport-moving     1445
Handlers-cleaners    1179
Farming-fishing       962
Tech-support          874
Protective-serv       631
Priv-house-serv       147
Armed-Forces            9
Name: count, dtype: int64

Variable RELATIONSHIP:
Valores unicos:
[' Not-in-family' ' Husband' ' Wife' ' Own-child' ' Unmarried'
 ' Other-relative']

relationship
Husband           11506
Not-in-family      7684
Own-child          4096
Unmarried          3317
Wife               1528
Other-relative      965
Name: count, dtype: int64

Variable RACE:
Valores unicos:
[' White' ' Black' ' Asian-Pac-Islander' ' Amer-Indian-Eskimo' ' Other']

race
White                 24438
Black                  3038
Asian-Pac-Islander     1038
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

Variable SEX:
Valores unicos:
[' Male' ' Female']

sex
Male      19246
Female     9850
Name: count, dtype: int64

Variable NATIVE_COUNTRY:
Valores unicos:
[' United-States' ' Cuba' ' Jamaica' ' India' ' ?' ' Mexico' ' South'
 ' Puerto-Rico' ' Honduras' ' England' ' Canada' ' Germany' ' Iran'
 ' Philippines' ' Italy' ' Poland' ' Columbia' ' Cambodia' ' Thailand'
 ' Ecuador' ' Laos' ' Taiwan' ' Haiti' ' Portugal' ' Dominican-Republic'
 ' El-Salvador' ' France' ' Guatemala' ' China' ' Japan' ' Yugoslavia'
 ' Peru' ' Outlying-US(Guam-USVI-etc)' ' Scotland' ' Trinadad&Tobago'
 ' Greece' ' Nicaragua' ' Vietnam' ' Hong' ' Ireland' ' Hungary'
 ' Holand-Netherlands']

native_country
United-States                 25721
Mexico                          633
?                               580
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        62
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
France                           29
Greece                           29
Ecuador                          28
Ireland                          23
Hong                             20
Trinadad&Tobago                  19
Cambodia                         19
Thailand                         18
Laos                             18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Honduras                         13
Hungary                          13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64

Variable INCOME:
Valores unicos:
[' <=50K' ' >50K']

income
<=50K    21886
>50K      7210
Name: count, dtype: int64

**Deberíamos  eliminar los espacios en blanco en las columnas tipo cadena y sustituir la interrogación "?" por el valor nulo**

## CORRECCIÓN DE ERRORES

### Espacios en blanco en los campos cadena

**Nota**: a una **Serie** cuyos datos sean texto (cadena, string), se le pueden **aplicar métodos de cadena** a la Serie completa **anteponiendo la palabra clave "str" en la notación punto.**

In [ ]:
def eliminar_espacios(columna):
    return columna.str.strip()

In [ ]:
df_adult.race[0]

' White'

In [ ]:
eliminar_espacios(df_adult.race)[0]

'White'

In [ ]:
df_adult[variables_categoricas] = df_adult[variables_categoricas].apply(eliminar_espacios)

for categorica in variables_categoricas:

    print(f'Variable {categorica.upper()}:')
    print('Valores unicos: ')
    print(df_adult[categorica].unique(), end='\n'*2)

Variable WORKCLASS:
Valores unicos:
['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov' '?'
 'Self-emp-inc' 'Without-pay' 'Never-worked']

Variable EDUCATION:
Valores unicos:
['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 'Assoc-voc' '7th-8th' 'Doctorate' 'Prof-school' '5th-6th' '10th'
 '1st-4th' 'Preschool' '12th']

Variable MARITAL_STATUS:
Valores unicos:
['Never-married' 'Married-civ-spouse' 'Divorced' 'Married-spouse-absent'
 'Separated' 'Married-AF-spouse' 'Widowed']

Variable OCCUPATION:
Valores unicos:
['Adm-clerical' 'Exec-managerial' 'Handlers-cleaners' 'Prof-specialty'
 'Other-service' 'Sales' 'Craft-repair' 'Transport-moving'
 'Farming-fishing' 'Machine-op-inspct' 'Tech-support' '?'
 'Protective-serv' 'Armed-Forces' 'Priv-house-serv']

Variable RELATIONSHIP:
Valores unicos:
['Not-in-family' 'Husband' 'Wife' 'Own-child' 'Unmarried' 'Other-relative']

Variable RACE:
Valores unicos:
['White' 'Black' 'Asian-Pac-Islander' 'Amer-Indian-Eskimo' 'Other']

Variable SEX:
Valores unicos:
['Male' 'Female']

Variable NATIVE_COUNTRY:
Valores unicos:
['United-States' 'Cuba' 'Jamaica' 'India' '?' 'Mexico' 'South'
 'Puerto-Rico' 'Honduras' 'England' 'Canada' 'Germany' 'Iran'
 'Philippines' 'Italy' 'Poland' 'Columbia' 'Cambodia' 'Thailand' 'Ecuador'
 'Laos' 'Taiwan' 'Haiti' 'Portugal' 'Dominican-Republic' 'El-Salvador'
 'France' 'Guatemala' 'China' 'Japan' 'Yugoslavia' 'Peru'
 'Outlying-US(Guam-USVI-etc)' 'Scotland' 'Trinadad&Tobago' 'Greece'
 'Nicaragua' 'Vietnam' 'Hong' 'Ireland' 'Hungary' 'Holand-Netherlands']

Variable INCOME:
Valores unicos:
['<=50K' '>50K']

### Codificar correctamente los datos nulos (sustituir "?")

In [ ]:
df_adult.replace('?', None, inplace=True)

for categorica in variables_categoricas:

    print(f'Variable {categorica.upper()}:')
    print('Valores unicos: ')
    print(df_adult[categorica].unique(), end='\n'*2)

Variable WORKCLASS:
Valores unicos:
['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov' None
 'Self-emp-inc' 'Without-pay' 'Never-worked']

Variable EDUCATION:
Valores unicos:
['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 'Assoc-voc' '7th-8th' 'Doctorate' 'Prof-school' '5th-6th' '10th'
 '1st-4th' 'Preschool' '12th']

Variable MARITAL_STATUS:
Valores unicos:
['Never-married' 'Married-civ-spouse' 'Divorced' 'Married-spouse-absent'
 'Separated' 'Married-AF-spouse' 'Widowed']

Variable OCCUPATION:
Valores unicos:
['Adm-clerical' 'Exec-managerial' 'Handlers-cleaners' 'Prof-specialty'
 'Other-service' 'Sales' 'Craft-repair' 'Transport-moving'
 'Farming-fishing' 'Machine-op-inspct' 'Tech-support' None
 'Protective-serv' 'Armed-Forces' 'Priv-house-serv']

Variable RELATIONSHIP:
Valores unicos:
['Not-in-family' 'Husband' 'Wife' 'Own-child' 'Unmarried' 'Other-relative']

Variable RACE:
Valores unicos:
['White' 'Black' 'Asian-Pac-Islander' 'Amer-Indian-Eskimo' 'Other']

Variable SEX:
Valores unicos:
['Male' 'Female']

Variable NATIVE_COUNTRY:
Valores unicos:
['United-States' 'Cuba' 'Jamaica' 'India' None 'Mexico' 'South'
 'Puerto-Rico' 'Honduras' 'England' 'Canada' 'Germany' 'Iran'
 'Philippines' 'Italy' 'Poland' 'Columbia' 'Cambodia' 'Thailand' 'Ecuador'
 'Laos' 'Taiwan' 'Haiti' 'Portugal' 'Dominican-Republic' 'El-Salvador'
 'France' 'Guatemala' 'China' 'Japan' 'Yugoslavia' 'Peru'
 'Outlying-US(Guam-USVI-etc)' 'Scotland' 'Trinadad&Tobago' 'Greece'
 'Nicaragua' 'Vietnam' 'Hong' 'Ireland' 'Hungary' 'Holand-Netherlands']

Variable INCOME:
Valores unicos:
['<=50K' '>50K']

In [ ]:
df_adult.isnull().sum()

age                  0
workclass         1632
education            0
marital_status       0
occupation        1639
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     580
income               0
dtype: int64

In [ ]:
df_adult.isnull().mean() * 100

age               0.000000
workclass         5.638647
fnlwgt            0.000000
education         0.000000
education_num     0.000000
marital_status    0.000000
occupation        5.660146
relationship      0.000000
race              0.000000
sex               0.000000
capital_gain      0.000000
capital_loss      0.000000
hours_per_week    0.000000
native_country    1.790486
income            0.000000
dtype: float64

## AÑADIR CAMPO CALCULADO 'capital_dif'. ELIMINAR LOS CAMPOS NO NECESARIOS.

In [ ]:
df_adult['capital_dif'] = df_adult['capital_gain'] - df_adult['capital_loss']

df_adult.head()

,age,workclass,education,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,capital_dif
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,2174
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,0

In [ ]:
df_adult.drop(columns=['capital_gain', 'capital_loss'], inplace=True)

df_adult.head()

,age,workclass,education,marital_status,occupation,relationship,race,sex,hours_per_week,native_country,income,capital_dif
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K,2174
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K,0
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K,0
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K,0
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K,0

## CODIFICAR LA VARIABLE OBJETIVO

Suele ser usual la variable objetivo si es categórica codificarla a número. Podemos utilizar el método **"replace"** que permite establecer las correspondencias:

In [ ]:
muestra_income = df_adult.sample(n=10, random_state=42).income

muestra_income

16803     >50K
8751      >50K
4842     <=50K
17164    <=50K
11346    <=50K
1399      >50K
3504     <=50K
27569    <=50K
24585    <=50K
10831     >50K
Name: income, dtype: object

In [ ]:
muestra_income.replace({'<=50K': 0, '>50K': 1})

<ipython-input-33-8453a0659a56>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  muestra_income.replace({'<=50K': 0, '>50K': 1})

16803    1
8751     1
4842     0
17164    0
11346    0
1399     1
3504     0
27569    0
24585    0
10831    1
Name: income, dtype: int64

In [ ]:
df_adult.income.value_counts()

<=50K    24720
>50K      7841
Name: income, dtype: int64

In [ ]:
df_adult.income[:10].to_list()

['<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '<=50K',
 '>50K',
 '>50K',
 '>50K']

In [ ]:
df_adult.income = df_adult.income.replace({'<=50K': 0, '>50K': 1})

df_adult.income.value_counts()

0    24720
1     7841
Name: income, dtype: int64

## NOS HACEMOS ALGUNAS PREGUNTAS.

**-¿Influye la educación en los ingresos?**

In [ ]:
df_adult.groupby(by=['education'])['income'].agg('mean').sort_values(ascending=False)

education
Doctorate       0.740920
Prof-school     0.734375
Masters         0.556587
Bachelors       0.414753
Assoc-voc       0.261216
Assoc-acdm      0.248360
Some-college    0.190235
HS-grad         0.159509
12th            0.076212
10th            0.066452
7th-8th         0.061920
9th             0.052529
11th            0.051064
5th-6th         0.048048
1st-4th         0.035714
Preschool       0.000000
Name: income, dtype: float64

**-¿Hay sesgo por la raza?**

In [ ]:
df_adult.groupby(by=['race'])['income'].agg('mean').sort_values(ascending=False)

race
Asian-Pac-Islander    0.265640
White                 0.255860
Black                 0.123880
Amer-Indian-Eskimo    0.115756
Other                 0.092251
Name: income, dtype: float64

**- Influencia cruzada**

In [ ]:
df_adult.groupby(by=['education','race'])['income'].agg(['mean','count']).sort_values(by='mean', ascending=False)

                                    mean  count
education   race
Prof-school Other               1.000000      4
            Amer-Indian-Eskimo  1.000000      2
Doctorate   Black               0.818182     11
            White               0.747967    369
Prof-school White               0.743191    514
...                                  ...    ...
5th-6th     Black               0.000000     21
9th         Other               0.000000      8
            Amer-Indian-Eskimo  0.000000      5
7th-8th     Other               0.000000     17
10th        Amer-Indian-Eskimo  0.000000     16

[79 rows x 2 columns]

## POR ÚLTIMO GUARDAR EL DATAFRAME PROCESADO

In [ ]:
df_adult.to_csv('./adult_final.csv', index=False)