In [ ]:
import pandas as pd
import numpy as np

# Puedes usar el siguiente dataset como base:
ruta = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(ruta)

In [ ]:
df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
286,287,1,3,"de Mulder, Mr. Theodore",male,30.0,0,0,345774,9.500,NaN,S
394,395,1,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...",female,24.0,0,2,PP 9549,16.700,G6,S
289,290,1,3,"Connolly, Miss. Kate",female,22.0,0,0,370373,7.750,NaN,Q
696,697,0,3,"Kelly, Mr. James",male,44.0,0,0,363592,8.050,NaN,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.550,E38,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.000,NaN,S
460,461,1,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.550,E12,S
508,509,0,3,"Olsen, Mr. Henry Margido",male,28.0,0,0,C 4001,22.525,NaN,S
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.0,0,2,363291,20.525,NaN,S
567,568,0,3,"Palsson, Mrs. Nils (Alma Cornelia Berglund)",female,29.0,0,4,349909,21.075,NaN,S

## Nivel 1: Exploración de datos
1. Carga el archivo CSV y muestra las primeras 5 filas.

In [ ]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

2. Muestra las últimas 10 filas del DataFrame.

In [ ]:
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

3. Usa .info() para obtener información general del DataFrame.

**Descripción detallada del dataset**:

PassengerId: Identificador único de cada pasajero.

Survived: Variable objetivo que indica si el pasajero sobrevivió (0=no, 1=sí).

Pclass: Clase del billete (1=Primera, 2=Segunda, 3=Tercera).

Name: Nombre del pasajero.

Sex: Sexo del pasajero.

Age: Edad del pasajero.

SibSp: Número de hermanos/cónyuges a bordo.

Parch: Número de padres/hijos a bordo.

Ticket: Número de billete.

Fare: Tarifa del billete.

Cabin: Número de camarote.

Embarked: Puerto de embarque (C=Cherburgo, Q=Queenstown, S=Southampton).

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

4. Utiliza .describe() para ver estadísticas descriptivas de las columnas numéricas.

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.Survived.value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
df.Survived.replace({0:'No',1:'Sí'},inplace=True)

df.Survived.value_counts()

<ipython-input-8-442a31a8cf99>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Survived.replace({0:'No',1:'Sí'},inplace=True)

Survived
No    549
Sí    342
Name: count, dtype: int64

- Hacemos lo smimo con la columna de "Clase" PClass:

In [ ]:
df.Pclass.value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
df.Pclass.replace({1: 'Primera', 2: 'Segunda', 3: 'Tercera'},inplace=True)

df.Pclass.value_counts()

<ipython-input-10-3024b86a6c2a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Pclass.replace({1: 'Primera', 2: 'Segunda', 3: 'Tercera'},inplace=True)

Pclass
Tercera    491
Primera    216
Segunda    184
Name: count, dtype: int64

In [ ]:
df.describe(include=['object'])

       Survived   Pclass                 Name   Sex  Ticket Cabin Embarked
count       891      891                  891   891     891   204      889
unique        2        3                  891     2     681   147        3
top          No  Tercera  Dooley, Mr. Patrick  male  347082    G6        S
freq        549      491                    1   577       7     4      644

5. Muestra los nombres de las columnas y los tipos de datos de cada una.

In [ ]:
df.dtypes

PassengerId      int64
Survived        object
Pclass          object
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

## Nivel 2: Selección y filtrado de datos

6. Selecciona solo la columna "Name" del DataFrame.

In [ ]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.Name

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

7. Selecciona las columnas "Name" y "Age".

In [ ]:
df[['Name','Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

8. Selecciona las primeras 10 filas usando .iloc[].

In [ ]:
df.iloc[0:10,:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,No,Tercera,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,Sí,Primera,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,Sí,Tercera,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,Sí,Primera,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,No,Tercera,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,No,Tercera,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,No,Primera,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,No,Tercera,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,Sí,Tercera,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,Sí,Segunda,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

9. Filtra a los pasajeros mayores de 60 años

In [ ]:
df[df.Age>60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,No,Segunda,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,No,Primera,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,No,Primera,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,No,Tercera,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,No,Primera,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,No,Primera,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,Sí,Primera,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,No,Tercera,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,No,Tercera,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,No,Primera,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,No,Primera,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,Sí,Tercera,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,No,Primera,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,No,Primera,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,No,Primera,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,Sí,Segunda,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,No,Primera,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,Sí,Primera,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,No,Segunda,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,No,Primera,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,Sí,Primera,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,No,Tercera,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [ ]:
# si me hubieran pedido el NOMBRE de los pasajeros mayores de 60 años

df[df.Age>60].Name

33                         Wheadon, Mr. Edward H
54                Ostby, Mr. Engelhart Cornelius
96                     Goldschmidt, Mr. George B
116                         Connors, Mr. Patrick
170                    Van der hoef, Mr. Wyckoff
252                    Stead, Mr. William Thomas
275            Andrews, Miss. Kornelia Theodosia
280                             Duane, Mr. Frank
326                    Nysveen, Mr. Johan Hansen
438                            Fortune, Mr. Mark
456                    Millet, Mr. Francis Davis
483                       Turkula, Mrs. (Hedwig)
493                      Artagaveytia, Mr. Ramon
545                 Nicholson, Mr. Arthur Ernest
555                           Wright, Mr. George
570                           Harris, Mr. George
625                        Sutton, Mr. Frederick
630         Barkworth, Mr. Algernon Henry Wilson
672                  Mitchell, Mr. Henry Michael
745                 Crosby, Capt. Edward Gifford
829    Stone, Mrs. George Nelson (Martha Evelyn)
851                          Svensson, Mr. Johan
Name: Name, dtype: object

In [ ]:
df.loc[df.Age>60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,No,Segunda,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,No,Primera,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,No,Primera,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,No,Tercera,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,No,Primera,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,No,Primera,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,Sí,Primera,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,No,Tercera,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,No,Tercera,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,No,Primera,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,No,Primera,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,Sí,Tercera,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,No,Primera,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,No,Primera,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,No,Primera,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,Sí,Segunda,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,No,Primera,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,Sí,Primera,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,No,Segunda,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,No,Primera,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,Sí,Primera,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,No,Tercera,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [ ]:
len(df.loc[df.Age>60])

22

In [ ]:
df.Pclass.unique()

array(['Tercera', 'Primera', 'Segunda'], dtype=object)

10. Filtra a los pasajeros que viajaban en primera clase y eran mujeres.

In [ ]:
df[(df.Pclass=='Primera') & (df.Sex=='female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,Sí,Primera,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,Sí,Primera,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,Sí,Primera,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,Sí,Primera,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,Sí,Primera,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,Sí,Primera,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,Sí,Primera,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,Sí,Primera,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,Sí,Primera,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,Sí,Primera,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

# <font color='red'>OJO: si utilizan el operador "and" da un error de ambiguedad

11. Cuenta cuántos valores nulos hay en cada columna.

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

12. Elimina todas las filas donde falte el valor de "Age".

In [ ]:
len(df)

891

In [ ]:
df.Age.isnull().sum()

np.int64(177)

In [ ]:
891-177

714

In [ ]:
df_drop_age = df.dropna(subset=['Age'])

len(df_drop_age)

714

13. Rellena los valores faltantes en "Embarked" con el valor más frecuente.

In [ ]:
print('Nulos ANTES de aplicar fillna: ', df.Embarked.isnull().sum())

print('\n'*2,'Ahora relleno con moda')
df.Embarked.fillna(df.Embarked.mode()[0],inplace=True)

print('\n'*2,'Nulos DESPUES de fillna: ', df.Embarked.isnull().sum())

Nulos ANTES de aplicar fillna:  2


 Ahora relleno con moda


 Nulos DESPUES de fillna:  0

<ipython-input-31-be93c94630ef>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Embarked.fillna(df.Embarked.mode()[0],inplace=True)

In [ ]:
%whos

Variable      Type         Data/Info
------------------------------------
df            DataFrame         PassengerId Survived<...>\n[891 rows x 12 columns]
df_drop_age   DataFrame         PassengerId Survived<...>\n[714 rows x 12 columns]
np            module       <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
pd            module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
ruta          str          https://raw.githubusercon<...>tasets/master/titanic.csv

In [ ]:
df.Embarked.isnull().sum()

np.int64(0)

14. Crea una nueva columna "EdadRedondeada" que contenga la edad redondeada.

In [ ]:
df.Age.sample(20)

143    19.0
96     71.0
442    25.0
853    16.0
772    57.0
588    22.0
141    22.0
485     NaN
499    24.0
337    41.0
725    20.0
107     NaN
416    34.0
366    60.0
77      NaN
162    26.0
734    23.0
408    21.0
733    23.0
382    32.0
Name: Age, dtype: float64

In [ ]:
df['EdadRedondeada'] = np.round(df.Age, decimals=2)

df.Age.sample(20)

809    33.0
104    37.0
70     32.0
762    20.0
602     NaN
324     NaN
830    15.0
818    43.0
364     NaN
572    36.0
229     NaN
819    10.0
362    45.0
351     NaN
24      8.0
791    16.0
316    24.0
120    21.0
0      22.0
21     34.0
Name: Age, dtype: float64

15. Reemplaza los valores de la columna "Sex" por "Hombre" y "Mujer".

In [ ]:
df.Sex.unique()

array(['male', 'female'], dtype=object)

In [ ]:
# si quiero que los cambios sean permanentes:
df.Sex.replace({'male':'Hombre','female':'Mujer'},inplace=True)

df.Sex.unique()

<ipython-input-37-d23d6fc35f3b>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Sex.replace({'male':'Hombre','female':'Mujer'},inplace=True)

array(['Hombre', 'Mujer'], dtype=object)

In [ ]:
# si quiero conservar el original (DF.SEX),
# guardo el cambio en una variable cualquiera (en este caso DF_CAMBIO_SEX)
df_cambio_sex = df.Sex.replace({'Hombre':'male','Mujer':'female'})

df_cambio_sex

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [ ]:
df.Sex

0      Hombre
1       Mujer
2       Mujer
3       Mujer
4      Hombre
        ...
886    Hombre
887     Mujer
888     Mujer
889    Hombre
890    Hombre
Name: Sex, Length: 891, dtype: object

16. Cuenta cuántos pasajeros hay por clase (Pclass).

In [ ]:
df.Pclass.unique()

array(['Tercera', 'Primera', 'Segunda'], dtype=object)

In [ ]:
df.Pclass.value_counts()

Pclass
Tercera    491
Primera    216
Segunda    184
Name: count, dtype: int64

In [ ]:
df.Pclass.value_counts(normalize=True)

Pclass
Tercera    0.551066
Primera    0.242424
Segunda    0.206510
Name: proportion, dtype: float64

In [ ]:
df.Pclass.value_counts(normalize=True) * 100

Pclass
Tercera    55.106622
Primera    24.242424
Segunda    20.650954
Name: proportion, dtype: float64

17. Calcula la media de edad por clase de pasajero.

In [ ]:
df.groupby('Pclass').Age.mean().round(2)

Pclass
Primera    38.23
Segunda    29.88
Tercera    25.14
Name: Age, dtype: float64

In [ ]:
df.groupby('Pclass').Age.agg(['mean', 'std']).round(0)

         mean   std
Pclass
Primera  38.0  15.0
Segunda  30.0  14.0
Tercera  25.0  12.0

18. Agrupa por "Sex" y "Pclass" y muestra la tarifa media pagada ("Fare").

In [ ]:
df.groupby(['Pclass','Sex']).Fare.mean().round(2)

Pclass   Sex
Primera  Hombre     67.23
         Mujer     106.13
Segunda  Hombre     19.74
         Mujer      21.97
Tercera  Hombre     12.66
         Mujer      16.12
Name: Fare, dtype: float64

16. Agrupa por "Embarked" y muestra cuántos sobrevivieron en cada puerto de embarque.

In [ ]:
df.groupby(['Embarked', 'Survived'])['Survived'].count()

Embarked  Survived
C         No           75
          Sí           93
Q         No           47
          Sí           30
S         No          427
          Sí          219
Name: Survived, dtype: int64

In [ ]:
df[df.Survived=='Sí'].groupby('Embarked').Survived.count()

Embarked
C     93
Q     30
S    219
Name: Survived, dtype: int64

In [ ]:
df[df.Survived=='Sí'].groupby('Embarked')['Survived'].count()

Embarked
C     93
Q     30
S    219
Name: Survived, dtype: int64

In [ ]:
df.Survived.unique()

array(['No', 'Sí'], dtype=object)

In [ ]:
df.groupby(['Embarked', 'Survived', 'Pclass'])['Survived'].count()

Embarked  Survived  Pclass
C         No        Primera     26
                    Segunda      8
                    Tercera     41
          Sí        Primera     59
                    Segunda      9
                    Tercera     25
Q         No        Primera      1
                    Segunda      1
                    Tercera     45
          Sí        Primera      1
                    Segunda      2
                    Tercera     27
S         No        Primera     53
                    Segunda     88
                    Tercera    286
          Sí        Primera     76
                    Segunda     76
                    Tercera     67
Name: Survived, dtype: int64

In [ ]:
#df[df.Survived=='Sí'].groupby('Embarked').Survived.agg(('Superv x puerto', 'count'))